version: '3.2'
services:
  mysqldb:
    container_name: mysqldb-${PROJECT_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
    image: mysql
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - './mysql-data:/var/lib/mysql'
    command: 'mysqld --innodb-flush-method=fsync --innodb-use-native-aio=0'
  redis:
    container_name: redis-${PROJECT_NAME}
    restart: on-failure
    image: redis:7.2.2
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./redis-data:/data
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
  rabbitmq:
    container_name: rabbitmq-${PROJECT_NAME}
    restart: on-failure
    image: rabbitmq:3-management
    ports:
      - '${RABBIT_UI_PORT}:15672'
      - '${RABBIT_API_PORT}:5672'
networks:
  default:
    name: '${NETWORK_NAME}'
