export const JOB_NAME = {
  TEST_RABBIT: 'TEST_RABBIT',
  NOTIFICATION: 'NOTIFICATION',
  EMAIL_FORGOT_PASSWORD: 'EMAIL_FORGOT_PASSWORD',
  UPDATE_TOTAL_CMT: 'UPDATE_TOTAL_CMT',
  UPDATE_TOTAL_REPLIES_CMT: 'UPDATE_TOTAL_REPLIES_CMT',
  UPDATE_TOTAL_LIKE: 'UPDATE_TOTAL_LIKE',
  UPDATE_TOTAL_FOLLOWING: 'UPDATE_TOTAL_FOLLOWING',
  UPDATE_TOTAL_FOLLOWERS: 'UPDATE_TOTAL_FOLLOWERS',
  UPDATE_TOTAL_AVG_PRODUCT_REVIEWS: 'UPDATE_TOTAL_AVG_PRODUCT_REVIEWS',
  NEW_MESSAGE_TO_ROOM: 'NEW_MESSAGE_TO_ROOM',
  ADMIN_REMOVE_CMT_SEND_NOTICE_TO_OWNER:
    'ADMIN_REMOVE_CMT_SEND_NOTICE_TO_OWNER',
  ADMIN_REMOVE_POST_SEND_NOTICE_TO_OWNER:
    'ADMIN_REMOVE_POST_SEND_NOTICE_TO_OWNER',
};
